using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Base;

namespace svStajOtomasyonu
{
    public partial class IsYeriStajBasvuru : Form
    {
        public IsYeriStajBasvuru()
        {
            InitializeComponent();



            // This line of code is generated by Data Source Configuration Wizard
            ogrenciTableAdapter2.Fill(stajdbIsYeriBelge1.Ogrenci);
        }
        public string yeniyol;
        SqlBaglanti baglan = new SqlBaglanti();
        public int isyeribasid;
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            OpenFileDialog dosya = new OpenFileDialog();
            dosya.Filter = "Pdf Dosyası |* *pdf; *nef | Tüm Dosyalar | *.*";
            dosya.ShowDialog();
            string dosyayolu = dosya.FileName;
            yeniyol = "C:\\Users\\sueda\\source\\repos\\svStajOtomasyonu\\svStajOtomasyonu" + "\\pdf\\" + Guid.NewGuid().ToString() + ".pdf";
            File.Copy(dosyayolu, yeniyol);
            pdfViewer1.LoadDocument(yeniyol);
            SqlCommand komut = new SqlCommand("Update StajBelgeleri set IsYeriPersonelForm=@p1 where IsYeriId=@p2", baglan.baglanti());
            komut.Parameters.AddWithValue("@p2", isyeribasid);
            komut.Parameters.AddWithValue("@p1", Path.GetFileName(yeniyol));
            komut.ExecuteNonQuery();
            baglan.baglanti().Close();
        }

        private void simpleButton8_Click(object sender, EventArgs e)
        {
            SqlCommand komut = new SqlCommand("Select * from StajBelgeleri where IsYeriId=@p1", baglan.baglanti());
            komut.Parameters.AddWithValue("@p1", isyeribasid);
            komut.ExecuteNonQuery();
            SqlDataReader read = komut.ExecuteReader();
            while (read.Read())
            {

                yeniyol = "C:\\Users\\sueda\\source\\repos\\svStajOtomasyonu\\svStajOtomasyonu" + "\\pdf\\" + read[9].ToString();
                pdfViewer2.LoadDocument(yeniyol);
            }
            baglan.baglanti().Close();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {
            
        }

        string id;
        private void gridView1_FocusedRowObjectChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventArgs e)
        {
            
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {

            SqlCommand komut = new SqlCommand("Update StajBelgeleri set IsYeriOnay=@p2 where Ogrenci=@p1", baglan.baglanti());
            komut.Parameters.AddWithValue("@p1", id);
            komut.Parameters.AddWithValue("@p2", "Onaylandı");
            komut.ExecuteNonQuery();
            SqlDataReader read = komut.ExecuteReader();
            
            baglan.baglanti().Close();

        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {

        }

        private void gridView1_FocusedRowObjectChanged_1(object sender, FocusedRowObjectChangedEventArgs e)
        {
            DataRow dr = gridView1.GetDataRow(gridView1.FocusedRowHandle);
            if (dr != null)
            {
                id = (dr["OgrenciId"].ToString());//Burada int hatası alabilirsin
                
                SqlCommand komut = new SqlCommand("Select * from StajBelgeleri where Ogrenci=@p1", baglan.baglanti());
                komut.Parameters.AddWithValue("@p1", id);
                komut.ExecuteNonQuery();
                SqlDataReader read = komut.ExecuteReader();
                while (read.Read())
                {

                    yeniyol = "C:\\Users\\sueda\\source\\repos\\svStajOtomasyonu\\svStajOtomasyonu" + "\\pdf\\" + read[5].ToString();
                    pdfViewer3.LoadDocument(yeniyol);
                }
                baglan.baglanti().Close();

            }
        }

        private void xtraTabPage3_Paint(object sender, PaintEventArgs e)
        {

            gridView1.Columns["OgrenciIsYeriId"].FilterInfo = new ColumnFilterInfo("[OgrenciIsYeriId]="+isyeribasid);//buraya iş yeri ıdsi özelliği gelecek
        }

        private void IsYeriStajBasvuru_Load(object sender, EventArgs e)
        {

        }
    }
}
