using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraGrid.Columns;

namespace svStajOtomasyonu
{
    public partial class IsYeriTask : Form
    {
        public IsYeriTask()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            ogrenciTableAdapter1.Fill(stajdbDataSetogr1.Ogrenci);
            // This line of code is generated by Data Source Configuration Wizard
            taskTableAdapter1.Fill(stajdbDataSetGorevsel1.Task);
        }
        SqlBaglanti baglan = new SqlBaglanti();
        int ogrid, isyeriid; 
            string isim, soyisim;
        public int isyeritaskid;
        int gorevId;
        string icerik;
        private void gridView1_FocusedRowObjectChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventArgs e)
        {
            
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            labelControl3.Visible = true;
            simpleButton2.Visible = true;
            textEdit1.Visible = true;
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            comboBox1.Items.Add(textEdit1.Text.ToString());
            labelControl3.Visible = false;
            simpleButton2.Visible = false;
            textEdit1.Visible = false;
        }

        private void IsYeriTask_Load(object sender, EventArgs e)
        {
            SqlCommand komut = new SqlCommand("Select DISTINCT GorevKonu from Task", baglan.baglanti());
            
            komut.ExecuteNonQuery();
            SqlDataReader read = komut.ExecuteReader();
            int i = 0;
            while (read.Read())
            {
                
                comboBox1.Items.Add(read.GetValue(0).ToString());
                
                
                

            }
            gridView1.Columns["OgrenciIsYeriId"].FilterInfo = new ColumnFilterInfo("[OgrenciIsYeriId]=" + isyeritaskid);
           // gridView2.Columns["OgrenciIsYeriId"].FilterInfo = new ColumnFilterInfo("[OgrenciIsYeriId]=" + isyeritaskid);
        }

        private void gridView2_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            
        }

        private void gridView2_FocusedRowObjectChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventArgs e)
        {
            DataRow dr = gridView2.GetDataRow(gridView2.FocusedRowHandle);
            if (dr != null)
            {

                labelControl9.Text = dr["OgrenIsim"].ToString() + " " + dr["OgrenciSoyisim"].ToString();
                labelControl6.Text = dr["GorevKonu"].ToString();
                

                gorevId = Convert.ToInt32(dr["GorevId"]);
                SqlCommand komut = new SqlCommand("Select * from Task where GorevId=@p1", baglan.baglanti());
                komut.Parameters.AddWithValue("@p1", gorevId);
                komut.ExecuteNonQuery();
                SqlDataReader read = komut.ExecuteReader();
                while (read.Read())
                {
                    icerik = read[6].ToString();

                }
                labelControl5.Text = icerik;

            }
        }

        public string yeniyol;
        private void simpleButton4_Click(object sender, EventArgs e)
        {
            xtraTabPage5.Show();
    
                SqlCommand komut = new SqlCommand("Select * from Task where GorevId=@p1", baglan.baglanti());
           
                komut.Parameters.AddWithValue("@p1", gorevId);
                komut.ExecuteNonQuery();
                SqlDataReader read = komut.ExecuteReader();
                while (read.Read())
                {
                    yeniyol = "C:\\Users\\sueda\\source\\repos\\svStajOtomasyonu\\svStajOtomasyonu" + "\\pdf\\" + read[7].ToString();
                    pdfViewer1.LoadDocument(yeniyol);
                }
                baglan.baglanti().Close();

               

            
        }

        private void xtraTabPage5_Paint(object sender, PaintEventArgs e)
        {
       

        }

        private void simpleButton5_Click(object sender, EventArgs e)
        {
            xtraTabPage6.Show();
        }

        private void simpleButton6_Click(object sender, EventArgs e)
        {
            int puan = (Convert.ToInt32(numericUpDown1.Value)+Convert.ToInt32(numericUpDown2.Value)+Convert.ToInt32(numericUpDown3.Value)); 
            SqlCommand komut = new SqlCommand("Update Task set GorevPuan=@p1, GorevPuanOnay=@p2, GorevYapildi=@p3 where GorevId=@p4", baglan.baglanti());
            komut.Parameters.AddWithValue("@p1", (puan/3).ToString());
            komut.Parameters.AddWithValue("@p2", "Puanlandırıldı");
            komut.Parameters.AddWithValue("@p3", "Görev Yapıldı");
            komut.Parameters.AddWithValue("@p4", gorevId);
        
            komut.ExecuteNonQuery();
            baglan.baglanti().Close();
            labelControl11.Text = (puan/3).ToString();
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void gridView1_FocusedRowObjectChanged_1(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventArgs e)
        {
            DataRow dr = gridView1.GetDataRow(gridView1.FocusedRowHandle);
            if (dr != null)
            {

                labelControl1.Text = dr["OgreciIsim"].ToString() + " " + dr["OgrenciSoyisim"].ToString();
                ogrid = Convert.ToInt32(dr["OgrenciId"]);
                isyeriid = Convert.ToInt32(dr["OgrenciIsYeriId"]);
                isim = dr["OgreciIsim"].ToString();
                soyisim = dr["OgrenciSoyisim"].ToString();

            }
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            SqlCommand komut = new SqlCommand("INSERT INTO Task (IsYeriId, OgrenciId, OgrenIsim, OgrenciSoyisim, GorevKonu, GorevIcerik) VALUES(@p1,@p2,@p3,@p4,@p5,@p6)", baglan.baglanti());
            komut.Parameters.AddWithValue("@p1", isyeriid);
            komut.Parameters.AddWithValue("@p2", ogrid);
            komut.Parameters.AddWithValue("@p3", isim);
            komut.Parameters.AddWithValue("@p4", soyisim);
            komut.Parameters.AddWithValue("@p5", comboBox1.Text.ToString());
            komut.Parameters.AddWithValue("@p6", textBox1.Text.ToString());
            komut.ExecuteNonQuery();
            baglan.baglanti().Close();
        }
    }
}
