using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace svStajOtomasyonu
{
    public partial class OgretmenStajSonuc : Form
    {

        SqlBaglanti baglan = new SqlBaglanti();
        int ogrid, isyeriid;
        string isim, soyisim;
         public int ogrsonucid;
        int gorevId;
        string icerik;
        public string yeniyol;
        public OgretmenStajSonuc()
        {
            InitializeComponent();

          
            // This line of code is generated by Data Source Configuration Wizard
            taskTableAdapter1.Fill(stajdbDataSetgorevogr1.Task);
        }

        private void gridView1_FocusedRowObjectChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventArgs e)
        {
            DataRow dr = gridView1.GetDataRow(gridView1.FocusedRowHandle);
            if (dr != null)
            {

                labelControl9.Text = dr["OgrenIsim"].ToString() + " " + dr["OgrenciSoyisim"].ToString();
                labelControl6.Text = dr["GorevKonu"].ToString();


                gorevId = Convert.ToInt32(dr["GorevId"]);
                SqlCommand komut = new SqlCommand("Select * from Task where GorevId=@p1", baglan.baglanti());
                komut.Parameters.AddWithValue("@p1", gorevId);
                komut.ExecuteNonQuery();
                SqlDataReader read = komut.ExecuteReader();
                while (read.Read())
                {
                    icerik = read[6].ToString();


                }
                labelControl5.Text = icerik;

            }
        }

        private void OgretmenStajSonuc_Load(object sender, EventArgs e)
        {
            
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
           
            xtraTabPage5.Show();
            SqlCommand komut = new SqlCommand("Select * from Task where GorevId=@p1", baglan.baglanti());

            komut.Parameters.AddWithValue("@p1", gorevId);
            komut.ExecuteNonQuery();
            SqlDataReader read = komut.ExecuteReader();
            while (read.Read())
            {

                yeniyol = "C:\\Users\\sueda\\source\\repos\\svStajOtomasyonu\\svStajOtomasyonu" + "\\pdf\\" + read[7].ToString();
                pdfViewer1.LoadDocument(yeniyol);
            }
            baglan.baglanti().Close();
        }
    }
}
