using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraGrid.Columns;

namespace svStajOtomasyonu
{
    public partial class OgrenciTask : Form
    {
        public OgrenciTask()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            taskTableAdapter1.Fill(stajdbDataSetgorevler1.Task);
        }
        string icerik;
        int gorevId;
        SqlBaglanti baglan = new SqlBaglanti();
        public string yeniyol;
        public int ogrIdTask;
        private void gridView1_FocusedRowObjectChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowObjectChangedEventArgs e)
        {
            DataRow dr = gridView1.GetDataRow(gridView1.FocusedRowHandle);
            if (dr != null)
            {

                labelControl3.Text = dr["GorevKonu"].ToString();
                gorevId = Convert.ToInt32(dr["GorevId"]);
                SqlCommand komut = new SqlCommand("Select * from Task where GorevId=@p1", baglan.baglanti());
                komut.Parameters.AddWithValue("@p1", gorevId);
                komut.ExecuteNonQuery();
                SqlDataReader read = komut.ExecuteReader();
                while (read.Read())
                {
                    icerik = read[6].ToString();
                   

                }
                labelControl5.Text = icerik;

            }
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            xtraTabPage2.Show();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            OpenFileDialog dosya = new OpenFileDialog();
            dosya.Filter = "Pdf Dosyası |* *pdf; *nef | Tüm Dosyalar | *.*";
            dosya.ShowDialog();
            string dosyayolu = dosya.FileName;
            yeniyol = "C:\\Users\\sueda\\source\\repos\\svStajOtomasyonu\\svStajOtomasyonu" + "\\pdf\\" + Guid.NewGuid().ToString() + ".pdf";
            File.Copy(dosyayolu, yeniyol);
            pdfViewer1.LoadDocument(yeniyol);
           
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            SqlCommand komut = new SqlCommand("Update Task set GorevPdf=@p1 where GorevId=@p2", baglan.baglanti());
            komut.Parameters.AddWithValue("@p2", gorevId);
            komut.Parameters.AddWithValue("@p1", Path.GetFileName(yeniyol));
            komut.ExecuteNonQuery();
            baglan.baglanti().Close();
        }

        private void OgrenciTask_Load(object sender, EventArgs e)
        {
            gridView1.Columns["OgrenciId"].FilterInfo = new ColumnFilterInfo("[OgrenciId]=" + ogrIdTask);
        }
    }
}
